services:
    wolnut:
        image: ghcr.io/tfourj/wolnut_webui:latest
        build: .
        container_name: wolnut
        network_mode: host
        restart: unless-stopped
        volumes:
            - ./config:/config
        environment:
            - ADMIN_USERNAME=admin
            - ADMIN_PASSWORD=changeme
            - WOLNUT_JWT_SECRET=change-this-to-a-long-random-secret
