[project]
name = "wolnut"
description = "A lightweight service designed to work alongside NUT to automatically send WOL packets to client systems after a power outage."
readme = "README.md"
authors = [{ name = "hardwarehaven", email = "hardwarehaven.media@gmail.com" }]
license = "MIT"
requires-python = ">=3.11"
dependencies = [
    "click>=8.2.1",
    "cryptography>=45.0.0",
    "fastapi>=0.110.0",
    "pyjwt>=2.8.0",
    "pyyaml>=6.0.2",
    "uvicorn[standard]>=0.29.0",
    "wakeonlan>=3.1.0",
]
dynamic = ["version"]

[tool.hatch.version]
path = "wolnut/__init__.py"

[tool.uv]
default-groups = []

[project.scripts]
wolnut = "wolnut.cli:wolnut"
wolnut-web = "wolnut.cli:web_only"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
coverage = [
    "coverage>=7.10.6",
    "pytest-cov>=6.2.1",
]
dev = [
    {include-group = "lint"},
    {include-group = "test"},
    {include-group = "coverage"}
]
lint = [
    "black>=25.1.0",
]
test = [
    "httpx2>=2.0.0",
    "pytest>=8.4.1",
    "pytest-mock>=3.14.1",
]
